sudo: false
language: python
python:
  - "2.7"
# Not supported (yet)
#  - "3.4"
#  - "3.5"
install: pip install tox-travis
script: tox
before_install:
  - pip install codecov
after_success:
  - codecov
